# Generated by Django 5.2.4 on 2025-08-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_integer',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
