# Generated by Django 5.2.4 on 2025-08-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_options_payment_checkout_request_id_and_more'),
    ]

    operations = [
    ]
