# Generated by Django 5.2.4 on 2025-08-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20250814_1609'),
    ]

    operations = [
    ]
