# Generated by Django 5.2.4 on 2025-08-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20250814_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
