# Generated by Django 5.2.4 on 2025-08-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_tickettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(choices=[('VIP', 'VIP'), ('REG', 'Regular'), ('GROUP', 'Group')], max_length=100),
        ),
    ]
